### ISSUE TITLE
Multiprocessing connection refused when training with VRD dataset

### ISSUE THREAD

**Issue by achireistefan** [jz462/Large-Scale-VRD.pytorch#23]
Hello all and thank you for the wonderful work!

I am facing this error when training:
> Traceback (most recent call last):
>   File "tools/train_net_step_rel.py", line 465, in <module>
>     main()
>   File "tools/train_net_step_rel.py", line 436, in main
>     training_stats.UpdateIterStats(net_outputs, inner_iter)
>   File "/home/ubuntu/StefanAchirei/Large-Scale-VRD.pytorch/lib/utils/training_stats_rel.py", line 82, in UpdateIterStats
>     for k, loss in model_out['losses'].items():
> TypeError: tuple indices must be integers or slices, not str
> Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f49b9aa3208>>
> Traceback (most recent call last):
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
>     self._shutdown_workers()
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
>     self.worker_result_queue.get()
>   File "/usr/lib/python3.6/multiprocessing/queues.py", line 337, in get
>     return _ForkingPickler.loads(res)
>   File "/home/ubuntu/.local/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
>     fd = df.detach()
>   File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
>     with _resource_sharer.get_connection(self._id) as conn:
>   File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
>     c = Client(address, authkey=process.current_process().authkey)
>   File "/usr/lib/python3.6/multiprocessing/connection.py", line 487, in Client
>     c = SocketClient(address)
>   File "/usr/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
>     s.connect(address)
> ConnectionRefusedError: [Errno 111] Connection refused

when running 
**python3 tools/train_net_step_rel.py --dataset vrd --cfg configs/e2e_relcnn_VGG16_8_epochs_vrd_y_loss_only.yaml --nw 8 --use_tfboard**

Not sure how to handle this. Any advice is welcomed, thank you.

**Comment by achireistefan** [comment]
The actual error was:
> File "/home/ubuntu/StefanAchirei/Large-Scale-VRD.pytorch/lib/utils/training_stats_rel.py", line 82, in UpdateIterStats
> for k, loss in model_out['losses'].items():
> TypeError: tuple indices must be integers or slices, not str

**model_out** needs index [0] in file **lib/utils/training_stats_rel.py** lines **81, 86, 94, 100** and in **tools/train_net_step_rel.py** at line **437**
