### ISSUE TITLE
Error occurs when setting up

### ISSUE THREAD

**Issue by zfy0314** [jz462/Large-Scale-VRD.pytorch#5]
Hi, thanks for sharing the code.
several errors occurred when I run ```sh setup.sh```, it seems like ```lib/model/nms/src/nms_cuda.c ```is missing. The full log is like this:
```
running build_ext
building 'utils.cython_bbox' extension
creating build
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/utils
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/numpy/core/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c utils/cython_bbox.c -o build/temp.linux-x86_64-3.7/utils/cython_bbox.o -Wno-cpp
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/utils
gcc -pthread -shared -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -L/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,-rpath=/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/utils/cython_bbox.o -o build/lib.linux-x86_64-3.7/utils/cython_bbox.cpython-37m-x86_64-linux-gnu.so
building 'utils.cython_nms' extension
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/numpy/core/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c utils/cython_nms.c -o build/temp.linux-x86_64-3.7/utils/cython_nms.o -Wno-cpp
utils/cython_nms.c: In function ‘__pyx_pf_5utils_10cython_nms_2soft_nms’:
utils/cython_nms.c:3394:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
utils/cython_nms.c:3905:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       __pyx_t_10 = ((__pyx_v_pos < __pyx_v_N) != 0);
                                  ^
gcc -pthread -shared -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -L/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,-rpath=/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/utils/cython_nms.o -o build/lib.linux-x86_64-3.7/utils/cython_nms.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/utils/cython_bbox.cpython-37m-x86_64-linux-gnu.so -> utils
copying build/lib.linux-x86_64-3.7/utils/cython_nms.cpython-37m-x86_64-linux-gnu.so -> utils
Compiling nms kernels by nvcc...
Including CUDA code.
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms
['/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms/src/nms_cuda_kernel.cu.o']
entering build.py
generating /tmp/tmpqm2d2pa7/_nms.c
setting the current directory to '/tmp/tmpqm2d2pa7'
running build_ext
building '_nms' extension
creating home
creating home/zfy
creating home/zfy/Data
creating home/zfy/Data/projects
creating home/zfy/Data/projects/isef
creating home/zfy/Data/projects/isef/Large-Scale-VRD
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms/src
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c _nms.c -o ./_nms.o -std=c99
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms/src/nms_cuda.c -o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms/src/nms_cuda.o -std=c99
gcc: error: /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/nms/src/nms_cuda.c: No such file or directory
Traceback (most recent call last):
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 38, in <module>
    ffi.build()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi pooling kernels by nvcc...
Including CUDA code.
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling
generating /tmp/tmpznpd9cv4/_roi_pooling.c
setting the current directory to '/tmp/tmpznpd9cv4'
running build_ext
building '_roi_pooling' extension
creating home
creating home/zfy
creating home/zfy/Data
creating home/zfy/Data/projects
creating home/zfy/Data/projects/isef
creating home/zfy/Data/projects/isef/Large-Scale-VRD
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c _roi_pooling.c -o ./_roi_pooling.o -std=c99
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling.c -o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling.o -std=c99
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling_cuda.c -o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling_cuda.o -std=c99
gcc -pthread -shared -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -L/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,-rpath=/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_roi_pooling.o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling.o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling_cuda.o /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_pooling/src/roi_pooling.cu.o -o ./_roi_pooling.so
Compiling roi crop kernels by nvcc...
Including CUDA code.
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop
generating /tmp/tmpfwwxvnm8/_roi_crop.c
setting the current directory to '/tmp/tmpfwwxvnm8'
running build_ext
building '_roi_crop' extension
creating home
creating home/zfy
creating home/zfy/Data
creating home/zfy/Data/projects
creating home/zfy/Data/projects/isef
creating home/zfy/Data/projects/isef/Large-Scale-VRD
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c _roi_crop.c -o ./_roi_crop.o -std=c99
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c -o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.o -std=c99
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBHWD_updateOutput’:
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:10:30: error: dereferencing pointer to incomplete type ‘THTensor {aka struct THTensor}’
   int batchsize = inputImages->size[0];
                              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBHWD_updateGradInput’:
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:190:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:189:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:188:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:187:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:186:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c: In function ‘BilinearSamplerBCHW_updateGradInput’:
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:441:14: warning: unused variable ‘inBottomRight’ [-Wunused-variable]
         real inBottomRight=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:440:14: warning: unused variable ‘inBottomLeft’ [-Wunused-variable]
         real inBottomLeft=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:439:14: warning: unused variable ‘inTopRight’ [-Wunused-variable]
         real inTopRight=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:438:14: warning: unused variable ‘inTopLeft’ [-Wunused-variable]
         real inTopLeft=0;
              ^
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/model/roi_crop/src/roi_crop.c:437:14: warning: unused variable ‘v’ [-Wunused-variable]
         real v=0;
              ^
Traceback (most recent call last):
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: CompileError: command 'gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
Including CUDA code.
/home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align
generating /tmp/tmpxcsjqb0r/_roi_align.c
setting the current directory to '/tmp/tmpxcsjqb0r'
running build_ext
building '_roi_align' extension
creating home
creating home/zfy
creating home/zfy/Data
creating home/zfy/Data/projects
creating home/zfy/Data/projects/isef
creating home/zfy/Data/projects/isef/Large-Scale-VRD
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align
creating home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align/src
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c _roi_align.c -o ./_roi_align.o -std=c99
gcc -pthread -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/zfy/anaconda2/envs/pytorch-old/lib/python3.7/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/zfy/anaconda2/envs/pytorch-old/include/python3.7m -c /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.c -o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.o -std=c99
gcc -pthread -shared -B /home/zfy/anaconda2/envs/pytorch-old/compiler_compat -L/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,-rpath=/home/zfy/anaconda2/envs/pytorch-old/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_roi_align.o ./home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align/src/roi_align_cuda.o /home/zfy/Data/projects/isef/Large-Scale-VRD/lib/modeling/roi_xfrom/roi_align/src/roi_align_kernel.cu.o -o ./_roi_align.so
```

I am running it on Ubuntu 16.04  with CUDA 9.2 properly installed, and my conda envrionment is listed below:
```
boto                      2.49.0                    <pip>
boto3                     1.9.130                   <pip>
botocore                  1.12.130                  <pip>
bz2file                   0.98                      <pip>
bzip2                     1.0.6             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2019.3.9             hecc5488_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2019.3.9                 py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cffi                      1.12.2                    <pip>
chardet                   3.0.4                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.7                    <pip>
decorator                 4.4.0                     <pip>
docutils                  0.14                      <pip>
gensim                    3.7.2                     <pip>
graphviz                  0.10.1                    <pip>
idna                      2.8                       <pip>
imageio                   2.5.0                     <pip>
jmespath                  0.9.4                     <pip>
kiwisolver                1.0.1                     <pip>
libffi                    3.2.1             he1b5a44_1006    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
matplotlib                3.0.3                     <pip>
ncurses                   6.1               hf484d3e_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
networkx                  2.3                       <pip>
numpy                     1.16.2                    <pip>
opencv-python             3.4.5.20                  <pip>
openssl                   1.1.1b               h14c3975_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
packaging                 19.0                      <pip>
Pillow                    6.0.0                     <pip>
pip                       19.0.3                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.7.1                     <pip>
pycocotools               2.0.0                     <pip>
pycparser                 2.19                      <pip>
pyparsing                 2.4.0                     <pip>
python                    3.7.3                h5b0a415_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.0                     <pip>
PyWavelets                1.0.3                     <pip>
PyYAML                    4.2b2                     <pip>
readline                  7.0               hf8c457e_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.21.0                    <pip>
s3transfer                0.2.0                     <pip>
scikit-image              0.15.0                    <pip>
scipy                     1.2.1                     <pip>
setuptools                41.0.0                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.12.0                    <pip>
smart-open                1.8.1                     <pip>
sqlite                    3.26.0            h67949de_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tensorboardX              1.6                       <pip>
tk                        8.6.9             h84994c4_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
torch                     0.4.1.post2               <pip>
torchvision               0.2.2.post3               <pip>
tqdm                      4.31.1                    <pip>
urllib3                   1.24.1                    <pip>
wheel                     0.33.1                   py37_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.4             h14c3975_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zlib                      1.2.11            h14c3975_1004    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
```
Could you please tell me how to solve it? Thanks in advance.

**Comment by jz462** [comment]
Hi @zfy0314,

I've updated the repo and this error should be gone by now.

**Comment by zfy0314** [comment]
Problem solved! Thanks
